"""empty message

Revision ID: 3ecad255d4d5
Revises: 
Create Date: 2025-11-25 11:18:57.734951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecad255d4d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('last_seen_online', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_name', sa.String(), nullable=False),
    sa.Column('offer_description', sa.String(), nullable=False),
    sa.Column('user_id_offeror', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_offeror'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id_sender', sa.Integer(), nullable=False),
    sa.Column('user_id_recipient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_recipient'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Boolean(), nullable=True),
    sa.Column('user_id_rater', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['userfeedback.id'], ),
    sa.ForeignKeyConstraint(['user_id_rater'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_rater', 'feedback_id', name='uq_user_feedback_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('userfeedback')
    op.drop_table('offer')
    op.drop_table('user')
    # ### end Alembic commands ###
