"""initial migration

Revision ID: 4a6c7b2a5f5e
Revises: 
Create Date: 2025-12-09 19:40:42.620833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6c7b2a5f5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('last_seen_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_name', sa.String(), nullable=False),
    sa.Column('offer_description', sa.String(), nullable=False),
    sa.Column('user_id_offeror', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_offeror'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id_sender', sa.Integer(), nullable=False),
    sa.Column('user_id_recipient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_recipient'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_sender'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'offer_id', name='unique_offer_category')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Boolean(), nullable=True),
    sa.Column('user_id_rater', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['userfeedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_rater'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_rater', 'feedback_id', name='uq_user_feedback_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('offer_category')
    op.drop_table('userfeedback')
    op.drop_table('offer')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
