"""added offer_status

Revision ID: a79021ba89ef
Revises: 4a6c7b2a5f5e
Create Date: 2025-12-16 20:30:13.961721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79021ba89ef'
down_revision = '4a6c7b2a5f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('offer_status', sa.String(), nullable=True))
    op.execute("UPDATE offer SET offer_status = 'АКТИВНО'")
    op.alter_column('offer', 'offer_status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'offer_status')
    # ### end Alembic commands ###
